#!/bin/bash

if [[ ! -e personnes ]]
then
    echo "Le fichiers personnes n'existe pas"
    exit 1
elif [[ ! -f personnes ]]
then
    echo "personnes n'est pas un fichiers"
    exit 2
fi

IFS=$'\n':' '

# Initialisation des fichiers garcons et filles (si ils existent deja, on les supprime)
touch garcons filles

cat personnes | while read -r nom genre
                do
                    if [[ $genre == "m" ]]
                    then
                        echo $nom >> garcons
                    elif [[ $genre == "f" ]]
                    then
                        echo $nom >> filles
                    else
                        echo "Genre incorrect: [m/f]"
                        exit 1
                    fi
                done
