#!/bin/bash

# $1 : temps en secondes

if [[ $# < 1 ]]; then
    echo "Il faut un argument"
    exit 1
elif [[ $1 != +([[:digit:]]) ]]; then
    echo "L'argument doit être un nombre"
    exit 2
fi

declare -i min=$(($1/60))
declare -i sec=$(($1%60))

echo "$min min : $sec sec"
