#!/bin/bash

if [[ $# < 1 ]]; then
    echo "Il faut spécifier le fichier de destination en argument"
    exit 1
fi

declare -i nb_line=0

> $1

while read -r line
do
    echo $line >> $1
    ((nb_line++))
done

echo $nb_line
