#!/bin/bash
# copier proprement
if [ $# -ne 2 ]
then 
echo "ERREUR: nombre arguments incorrect"
exit 1
fi 
if [ ! -r $1 ]
then
echo "ERREUR: la source n'est pas accessible"
exit 2
fi
if [ ! -f $1 ]
then
echo "ERREUR: la source n'est pas un fichier"
exit 3
fi
if [ ! -e $2 ]
then
echo "ERREUR: la destination n'existe pas"
exit 4
fi
rep_dst=`dirname $2` #nom de repertoire
if [ -w $rep_dst ]
then
echo "ERREUR: le répertoire n'est pas accessible"
exit 5
fi
if cp $1 $2 > /dev/null
then :
else
echo "ERREUR: la copie a echouée"
exit 6
fi