#!/bin/bash

echo "Gestion d'agenda téléphonique"

function print_menu {
    echo "*********************************"
    echo "1. Ajouter une nouvelle fiche"
    echo "2. Recherche une fiche"
    echo "3. Détruire une fiche"
    echo "4. Modifier une fiche"
    echo "5. Lister l'anuaire"
    echo "6. Fin"
}

function verify_phone_number {
    [[ ! ($1 == +([[:digit:]]) && ${#1} == 10) ]] && return 1
    grep -q "$1" agenda.csv && return 2
    return 0
}

function verify_name {
    [[ ! ($1 == +([[:alpha:]]) && ${#1} > 2) ]] && return 1
    return 0
}

function add_fiche {
    while read -p "Nom : " nom
    do
        verify_name $nom
        case $? in
            0)
                break
                ;;
            1)
                echo "Le nom doit être composé de 3 lettres au minimum"
                ;;
        esac
    done
    while read -p "Téléphone : " tel
    do
        verify_phone_number $tel
        case $? in
            0)
                echo "$nom,$tel" >> agenda.csv
                echo "Fiche ajoutée avec succès"
                break
                ;;
            1)
                echo "Le numéro de téléphone doit être composé de 10 chiffres"
                ;;
            2)
                echo "Le numéro de téléphone existe déjà"
                ;;
        esac
    done
}

function search_fiche {
    while read -p "Nom : " nom
    do
        [[ ! ($nom == +([[:alpha:]]) && ${#nom} > 1) ]] && echo "Le nom doit être composé seulement de lettres et de 2 lettres au minimum" && continue
        break
    done    
    grep -i "$nom" agenda.csv > agenda.csv.tmp
    if [[ -s agenda.csv.tmp ]]; then
        cat -n agenda.csv.tmp
    else
        echo "Aucun résultat pour $nom"
    fi
    rm agenda.csv.tmp
}

function destroy_fiche {
    read -p "Téléphone : " tel
    verify_phone_number $tel
    case $? in
        0)
            echo "Le numéro de téléphone n'existe pas"
            ;;
        1)
            echo "Le numéro de téléphone doit être composé de 10 chiffres"
            ;;
        2)
            grep -v $tel agenda.csv > agenda.csv.tmp
            cp agenda.csv.tmp agenda.csv
            rm agenda.csv.tmp
            echo "Fiche supprimée avec succès"
            ;;
    esac
}

function modify_fiche {
    read -p "Téléphone : " tel
    if [[ ! ($tel == +([[:digit:]]) && ${#tel} == 10) ]]; then
        echo "Le numéro de téléphone doit être composé de 10 chiffres"
        return 1
    fi
    fiche=$(grep $tel agenda.csv)
    if [[ -z $fiche ]]; then
        echo "Le numéro de téléphone n'existe pas"
        return 2    
    fi
    read -p "Nouveau nom : " N_nom
    [[ -z $N_nom ]] && N_nom=${fiche%%,*}
    echo "Nouveau nom : $N_nom"
    while read -p "Nouveau téléphone : " N_tel
    do
        [[ -z $N_tel ]] && N_tel=${fiche#*,} && break
        [[ ! ($N_tel == +([[:digit:]]) && ${#N_tel} == 10) ]] && echo "Le numéro de téléphone doit être composé de 10 chiffres" && continue
        grep -q "$N_tel" agenda.csv && echo "Le numéro de téléphone existe déjà" && return 3
        echo "Nouveau téléphone : $N_tel" && break
    done
    grep -v $tel agenda.csv > agenda.csv.tmp
    echo "$N_nom,$N_tel" >> agenda.csv.tmp
    cp agenda.csv.tmp agenda.csv
    rm agenda.csv.tmp
    echo "Fiche modifiée avec succès"
}

function list_fiche {
    if [[ -s agenda.csv ]]; then
        cat -n agenda.csv
    else
        echo "Agenda vide"
    fi
}

# Main

# Création du fichier agenda.csv s'il n'existe pas
[[ -f agenda.csv ]] || touch agenda.csv

# Menu
while :
do
    print_menu
    read -p "Votre choix ? : "
    clear
    echo "*********************************"
    case $REPLY in
        1) 
            echo "*** Ajout d'une nouvelle fiche"
            add_fiche
            ;;
        2)
            echo "*** Recherche d'une fiche"
            search_fiche
            ;;
        3)
            echo "*** Destruction d'une fiche"
            destroy_fiche
            ;;
        4)
            echo "*** Modification d'une fiche"
            modify_fiche
            ;;
        5)
            echo "*** Liste de l'annuaire"
            list_fiche
            ;;
        6)
            echo "*** Fin"
            break
            ;;
        *)
            echo "*** Choix invalide"
            ;;
    esac
done
