#!/bin/bash

function calcul
{
  case $2 in
    +) echo $(( $1 + $3 ));;
    -) echo $(( $1 - $3 ));;
    x) echo $(( $1 * $3 ));;
    /) 
      [[ $3 == 0 ]] && { echo "Division par 0 impossible"; exit 1; }
      echo $(( $1 / $3 ));;
  esac
}

if [[ $# != 3 ]]; then
  read -p "Saisir votre opération sous forme \"op1 operaeur op2\" : "
  set $REPLY
  set $@
fi

if [[ $1 != +([[:digit:]]) && $3 != +([[:digit:]]) ]]; then
  echo "Les opérandes doivent être des nombres"
  exit 1
fi

if [[ $2 != @([*\-+/]) ]]; then
  echo "L'opérateur doit être +, -, x ou /"
  exit 1
fi

echo "Le résultat est : $(calcul $1 $2 $3)"
